### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by Taknax** [mchorse/extendedreach#1]
Is ER client?
If no. Does the config file on the server get forced? Also can i disable the manipulating somehow?

**Comment by mchorse** [comment]
No, it's both sides. And yes, it gets forced, but I'm not sure why would you want to disable it instead of deinstalling it?

**Comment by Taknax** [comment]
Sorry. My english is not the best. You answered almost. What i meaned was: if i setup on server other can change or not. I am very happy they cant, because config get forced by the server. I dont want disable the mod. I just want disable other player from changing the reach. Thank you very much for this useful mod.

**Comment by mchorse** [comment]
Ah, I understand the question now. I honestly haven’t used the mod in a year or so, so I can’t tell. Could you test it out?

**Comment by Taknax** [comment]
Of course. I am gonna tell you the result.

**Comment by Taknax** [comment]
It works very well and without issues in multiplayer, but the config get not forced. Also a non OP player can change reach value. If the non OP player change the reach value, then its not get changed in the server config, but the non OP player can use the higher reach.
Also everything works well, but server config is not forced.

**Comment by mchorse** [comment]
Awesome! Thanks for writing back!
